"""rename TripPhoto fields: thumbnail_url->thumb_url, display_order->order

Revision ID: 5d9af741906e
Revises: f1e9c89bc7ce
Create Date: 2025-12-28 22:36:12.346891+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d9af741906e"
down_revision: Union[str, None] = "f1e9c89bc7ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trip_photos", schema=None) as batch_op:
        batch_op.add_column(sa.Column("thumb_url", sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column("order", sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f("idx_photo_order"))
        batch_op.create_index("idx_photo_order", ["trip_id", "order"], unique=False)
        batch_op.drop_column("thumbnail_url")
        batch_op.drop_column("display_order")

    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.alter_column(
            "start_date", existing_type=sa.DATETIME(), type_=sa.Date(), existing_nullable=False
        )
        batch_op.alter_column(
            "end_date", existing_type=sa.DATETIME(), type_=sa.Date(), existing_nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.alter_column(
            "end_date", existing_type=sa.Date(), type_=sa.DATETIME(), existing_nullable=True
        )
        batch_op.alter_column(
            "start_date", existing_type=sa.Date(), type_=sa.DATETIME(), existing_nullable=False
        )

    with op.batch_alter_table("trip_photos", schema=None) as batch_op:
        batch_op.add_column(sa.Column("display_order", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("thumbnail_url", sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_index("idx_photo_order")
        batch_op.create_index(
            batch_op.f("idx_photo_order"), ["trip_id", "display_order"], unique=False
        )
        batch_op.drop_column("order")
        batch_op.drop_column("thumb_url")

    # ### end Alembic commands ###
