"""Add file_size, width, height to trip_photos

Revision ID: ed91566c4f43
Revises: 5d9af741906e
Create Date: 2025-12-30 00:44:41.782354+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed91566c4f43"
down_revision: Union[str, None] = "5d9af741906e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trip_photos", schema=None) as batch_op:
        batch_op.add_column(sa.Column("file_size", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("width", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("height", sa.Integer(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trip_photos", schema=None) as batch_op:
        batch_op.drop_column("height")
        batch_op.drop_column("width")
        batch_op.drop_column("file_size")

    # ### end Alembic commands ###
