"""add travel diary models

Revision ID: f1e9c89bc7ce
Revises: 004
Create Date: 2025-12-28 20:15:08.185872+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "f1e9c89bc7ce"
down_revision: Union[str, None] = "004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("tag_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("normalized", sa.String(length=50), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("tag_id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("normalized"),
    )
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index("idx_tag_normalized", ["normalized"], unique=False)
        batch_op.create_index("idx_tag_usage", ["usage_count"], unique=False)

    op.create_table(
        "trips",
        sa.Column("trip_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", name="tripstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("distance_km", sa.Float(), nullable=True),
        sa.Column(
            "difficulty",
            sa.Enum(
                "EASY",
                "MODERATE",
                "DIFFICULT",
                "VERY_DIFFICULT",
                name="tripdifficulty",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("trip_id"),
    )
    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.create_index("idx_trip_created", ["created_at"], unique=False)
        batch_op.create_index("idx_trip_published", ["published_at"], unique=False)
        batch_op.create_index("idx_trip_user_status", ["user_id", "status"], unique=False)

    op.create_table(
        "trip_locations",
        sa.Column("location_id", sa.String(length=36), nullable=False),
        sa.Column("trip_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.trip_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("location_id"),
    )
    with op.batch_alter_table("trip_locations", schema=None) as batch_op:
        batch_op.create_index("idx_location_sequence", ["trip_id", "sequence"], unique=False)
        batch_op.create_index("idx_location_trip", ["trip_id"], unique=False)

    op.create_table(
        "trip_photos",
        sa.Column("photo_id", sa.String(length=36), nullable=False),
        sa.Column("trip_id", sa.String(length=36), nullable=False),
        sa.Column("photo_url", sa.String(length=500), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=500), nullable=False),
        sa.Column("caption", sa.String(length=500), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.trip_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("photo_id"),
    )
    with op.batch_alter_table("trip_photos", schema=None) as batch_op:
        batch_op.create_index("idx_photo_order", ["trip_id", "display_order"], unique=False)
        batch_op.create_index("idx_photo_trip", ["trip_id"], unique=False)

    op.create_table(
        "trip_tags",
        sa.Column("trip_id", sa.String(length=36), nullable=False),
        sa.Column("tag_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.tag_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.trip_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("trip_id", "tag_id"),
    )
    with op.batch_alter_table("trip_tags", schema=None) as batch_op:
        batch_op.create_index("idx_trip_tag_tag", ["tag_id"], unique=False)
        batch_op.create_index("idx_trip_tag_trip", ["trip_id"], unique=False)

    with op.batch_alter_table("achievements", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=sa.DATETIME(), server_default=None, existing_nullable=False
        )
        batch_op.drop_index(batch_op.f("ix_achievements_code"))
        batch_op.create_index(batch_op.f("ix_achievements_code"), ["code"], unique=True)

    with op.batch_alter_table("follows", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=sa.DATETIME(), server_default=None, existing_nullable=False
        )

    with op.batch_alter_table("password_resets", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=sa.DATETIME(), server_default=None, existing_nullable=False
        )

    with op.batch_alter_table("user_achievements", schema=None) as batch_op:
        batch_op.alter_column(
            "awarded_at", existing_type=sa.DATETIME(), server_default=None, existing_nullable=False
        )
        batch_op.drop_constraint(batch_op.f("uq_user_achievement"), type_="unique")

    with op.batch_alter_table("user_profiles", schema=None) as batch_op:
        batch_op.alter_column(
            "show_email", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "show_location",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "followers_count",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "following_count",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at", existing_type=sa.DATETIME(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "updated_at", existing_type=sa.DATETIME(), server_default=None, existing_nullable=False
        )
        batch_op.drop_index(batch_op.f("ix_user_profiles_user_id"))
        batch_op.create_index(batch_op.f("ix_user_profiles_user_id"), ["user_id"], unique=True)

    with op.batch_alter_table("user_stats", schema=None) as batch_op:
        batch_op.alter_column(
            "total_trips", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "total_kilometers",
            existing_type=sa.FLOAT(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "countries_visited",
            existing_type=sqlite.JSON(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "total_photos", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "achievements_count",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at", existing_type=sa.DATETIME(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "updated_at", existing_type=sa.DATETIME(), server_default=None, existing_nullable=False
        )
        batch_op.drop_index(batch_op.f("ix_user_stats_user_id"))
        batch_op.create_index(batch_op.f("ix_user_stats_user_id"), ["user_id"], unique=True)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "is_verified", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "created_at", existing_type=sa.DATETIME(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "updated_at", existing_type=sa.DATETIME(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "failed_login_attempts",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=False)
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=False)
        batch_op.alter_column(
            "failed_login_attempts",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_verified",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("'1'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("user_stats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_stats_user_id"))
        batch_op.create_index(batch_op.f("ix_user_stats_user_id"), ["user_id"], unique=False)
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "achievements_count",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "total_photos",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "countries_visited",
            existing_type=sqlite.JSON(),
            server_default=sa.text("'[]'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "total_kilometers",
            existing_type=sa.FLOAT(),
            server_default=sa.text("'0.0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "total_trips",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("user_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_profiles_user_id"))
        batch_op.create_index(batch_op.f("ix_user_profiles_user_id"), ["user_id"], unique=False)
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "following_count",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "followers_count",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "show_location",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("'1'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "show_email",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("user_achievements", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_user_achievement"), ["user_id", "achievement_id"]
        )
        batch_op.alter_column(
            "awarded_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("password_resets", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("follows", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("achievements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_achievements_code"))
        batch_op.create_index(batch_op.f("ix_achievements_code"), ["code"], unique=False)
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("trip_tags", schema=None) as batch_op:
        batch_op.drop_index("idx_trip_tag_trip")
        batch_op.drop_index("idx_trip_tag_tag")

    op.drop_table("trip_tags")
    with op.batch_alter_table("trip_photos", schema=None) as batch_op:
        batch_op.drop_index("idx_photo_trip")
        batch_op.drop_index("idx_photo_order")

    op.drop_table("trip_photos")
    with op.batch_alter_table("trip_locations", schema=None) as batch_op:
        batch_op.drop_index("idx_location_trip")
        batch_op.drop_index("idx_location_sequence")

    op.drop_table("trip_locations")
    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.drop_index("idx_trip_user_status")
        batch_op.drop_index("idx_trip_published")
        batch_op.drop_index("idx_trip_created")

    op.drop_table("trips")
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index("idx_tag_usage")
        batch_op.drop_index("idx_tag_normalized")

    op.drop_table("tags")
    # ### end Alembic commands ###
