"""Add social network tables (likes, comments, shares, notifications)

Revision ID: 44e29a9f8684
Revises: 9538015d4196
Create Date: 2026-01-17 00:22:29.628635+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44e29a9f8684"
down_revision: Union[str, None] = "9538015d4196"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create likes table
    op.create_table(
        'likes',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('user_id', sa.String(36), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('trip_id', sa.String(36), sa.ForeignKey('trips.trip_id', ondelete='CASCADE'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint('user_id', 'trip_id', name='uq_user_trip_like')
    )
    op.create_index('idx_like_user', 'likes', ['user_id'])
    op.create_index('idx_like_trip', 'likes', ['trip_id'])

    # Create comments table
    op.create_table(
        'comments',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('user_id', sa.String(36), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('trip_id', sa.String(36), sa.ForeignKey('trips.trip_id', ondelete='CASCADE'), nullable=False),
        sa.Column('content', sa.Text, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_edited', sa.Boolean, nullable=False, server_default='0')
    )
    op.create_index('idx_comment_trip', 'comments', ['trip_id', 'created_at'])
    op.create_index('idx_comment_user', 'comments', ['user_id'])

    # Create shares table
    op.create_table(
        'shares',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('user_id', sa.String(36), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('trip_id', sa.String(36), sa.ForeignKey('trips.trip_id', ondelete='CASCADE'), nullable=False),
        sa.Column('comment', sa.Text, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False)
    )
    op.create_index('idx_share_user', 'shares', ['user_id'])
    op.create_index('idx_share_trip', 'shares', ['trip_id'])

    # Create notifications table
    op.create_table(
        'notifications',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('user_id', sa.String(36), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('type', sa.String(20), nullable=False),
        sa.Column('actor_id', sa.String(36), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('trip_id', sa.String(36), sa.ForeignKey('trips.trip_id', ondelete='CASCADE'), nullable=False),
        sa.Column('content', sa.Text, nullable=True),
        sa.Column('is_read', sa.Boolean, nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False)
    )
    op.create_index('idx_notification_user_unread', 'notifications', ['user_id', 'is_read', 'created_at'])

    # Create notification_archive table
    op.create_table(
        'notification_archive',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('user_id', sa.String(36), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('type', sa.String(20), nullable=False),
        sa.Column('actor_id', sa.String(36), nullable=True),
        sa.Column('trip_id', sa.String(36), nullable=True),
        sa.Column('content', sa.Text, nullable=True),
        sa.Column('is_read', sa.Boolean, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('archived_at', sa.DateTime(timezone=True), nullable=False)
    )
    op.create_index('idx_notification_archive_user', 'notification_archive', ['user_id', 'archived_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notification_archive_user', 'notification_archive')
    op.drop_table('notification_archive')
    op.drop_index('idx_notification_user_unread', 'notifications')
    op.drop_table('notifications')
    op.drop_index('idx_share_trip', 'shares')
    op.drop_index('idx_share_user', 'shares')
    op.drop_table('shares')
    op.drop_index('idx_comment_user', 'comments')
    op.drop_index('idx_comment_trip', 'comments')
    op.drop_table('comments')
    op.drop_index('idx_like_trip', 'likes')
    op.drop_index('idx_like_user', 'likes')
    op.drop_table('likes')
    # ### end Alembic commands ###
