"""add is_private field to trips

Revision ID: 1f920057696f
Revises: 40493bf1c72c
Create Date: 2026-02-04 15:10:08.031342+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f920057696f"
down_revision: Union[str, None] = "40493bf1c72c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_private", sa.Boolean(), nullable=False, server_default="0")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.drop_column("is_private")

    # ### end Alembic commands ###
