"""Add cycling_types table for dynamic type management

Revision ID: 572d49f6a7f3
Revises: ed91566c4f43
Create Date: 2026-01-08 10:46:44.420342+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "572d49f6a7f3"
down_revision: Union[str, None] = "ed91566c4f43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cycling_types",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cycling_types", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cycling_types_code"), ["code"], unique=True)
        batch_op.create_index(batch_op.f("ix_cycling_types_is_active"), ["is_active"], unique=False)

    with op.batch_alter_table("trip_photos", schema=None) as batch_op:
        batch_op.alter_column(
            "file_size", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "width", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "height", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trip_photos", schema=None) as batch_op:
        batch_op.alter_column(
            "height",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "width",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "file_size",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("cycling_types", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cycling_types_is_active"))
        batch_op.drop_index(batch_op.f("ix_cycling_types_code"))

    op.drop_table("cycling_types")
    # ### end Alembic commands ###
