"""add_extreme_difficulty_level

Revision ID: 40493bf1c72c
Revises: cc4806b151bd
Create Date: 2026-01-28 23:31:29.786808+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import JSON


# revision identifiers, used by Alembic.
revision: str = "40493bf1c72c"
down_revision: Union[str, None] = "cc4806b151bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications_archive",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("trip_id", sa.String(length=36), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications_archive", schema=None) as batch_op:
        batch_op.create_index("ix_notifications_archive_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_notifications_archive_user", ["user_id"], unique=False)

    with op.batch_alter_table("notification_archive", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_notification_archive_user"))

    op.drop_table("notification_archive")
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.alter_column(
            "is_edited", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
        )
        batch_op.drop_index(batch_op.f("idx_comment_trip"))
        batch_op.drop_index(batch_op.f("idx_comment_user"))
        batch_op.create_index("ix_comments_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_comments_trip_id", ["trip_id"], unique=False)
        batch_op.create_index("ix_comments_user_id", ["user_id"], unique=False)

    with op.batch_alter_table("gpx_files", schema=None) as batch_op:
        batch_op.alter_column(
            "processing_status",
            existing_type=sa.VARCHAR(length=20),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "uploaded_at",
            existing_type=sa.TIMESTAMP(),
            server_default=None,
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "processed_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.drop_index(batch_op.f("idx_gpx_files_status"))
        batch_op.drop_index(batch_op.f("idx_gpx_files_trip"))

    with op.batch_alter_table("likes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_like_trip"))
        batch_op.drop_index(batch_op.f("idx_like_user"))
        batch_op.create_index("ix_likes_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_likes_trip_id", ["trip_id"], unique=False)
        batch_op.create_index("ix_likes_user_id", ["user_id"], unique=False)

    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.alter_column(
            "is_read", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
        )
        batch_op.drop_index(batch_op.f("idx_notification_user_unread"))
        batch_op.create_index("ix_notifications_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_notifications_user_read", ["user_id", "is_read"], unique=False)

    with op.batch_alter_table("points_of_interest", schema=None) as batch_op:
        batch_op.alter_column(
            "poi_type",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.Enum(
                "viewpoint",
                "town",
                "water",
                "accommodation",
                "restaurant",
                "mountain_pass",
                "other",
                name="poi_type_enum",
                native_enum=False,
            ),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at", existing_type=sa.TIMESTAMP(), server_default=None, existing_nullable=False
        )
        batch_op.drop_index(batch_op.f("idx_poi_sequence"))
        batch_op.drop_index(batch_op.f("idx_poi_trip"))
        batch_op.drop_index(batch_op.f("idx_poi_type"))
        batch_op.create_index(
            batch_op.f("ix_points_of_interest_poi_type"), ["poi_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_points_of_interest_trip_id"), ["trip_id"], unique=False
        )

    with op.batch_alter_table("route_statistics", schema=None) as batch_op:
        batch_op.alter_column(
            "stats_id", existing_type=sa.TEXT(), type_=sa.String(length=36), nullable=False
        )
        batch_op.alter_column(
            "gpx_file_id",
            existing_type=sa.TEXT(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "avg_speed_kmh", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True
        )
        batch_op.alter_column(
            "max_speed_kmh", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True
        )
        batch_op.alter_column(
            "total_time_minutes", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True
        )
        batch_op.alter_column(
            "moving_time_minutes", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True
        )
        batch_op.alter_column(
            "avg_gradient", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True
        )
        batch_op.alter_column(
            "max_gradient", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True
        )
        batch_op.alter_column(
            "top_climbs",
            existing_type=sa.TEXT(),
            type_=JSON(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            server_default=None,
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
        )
        batch_op.drop_index(batch_op.f("idx_route_stats_gpx"))

    with op.batch_alter_table("shares", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_share_trip"))
        batch_op.drop_index(batch_op.f("idx_share_user"))
        batch_op.create_index("ix_shares_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_shares_trip_id", ["trip_id"], unique=False)
        batch_op.create_index("ix_shares_user_id", ["user_id"], unique=False)

    with op.batch_alter_table("track_points", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_track_points_gpx"))
        batch_op.drop_index(batch_op.f("idx_track_points_seq"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track_points", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_track_points_seq"), ["gpx_file_id", "sequence"], unique=False
        )
        batch_op.create_index(batch_op.f("idx_track_points_gpx"), ["gpx_file_id"], unique=False)

    with op.batch_alter_table("shares", schema=None) as batch_op:
        batch_op.drop_index("ix_shares_user_id")
        batch_op.drop_index("ix_shares_trip_id")
        batch_op.drop_index("ix_shares_created_at")
        batch_op.create_index(batch_op.f("idx_share_user"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("idx_share_trip"), ["trip_id"], unique=False)

    with op.batch_alter_table("route_statistics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_route_stats_gpx"), ["gpx_file_id"], unique=False)
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            type_=sa.TIMESTAMP(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "top_climbs",
            existing_type=src.models.route_statistics.JSONType(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "max_gradient", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True
        )
        batch_op.alter_column(
            "avg_gradient", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True
        )
        batch_op.alter_column(
            "moving_time_minutes", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True
        )
        batch_op.alter_column(
            "total_time_minutes", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True
        )
        batch_op.alter_column(
            "max_speed_kmh", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True
        )
        batch_op.alter_column(
            "avg_speed_kmh", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True
        )
        batch_op.alter_column(
            "gpx_file_id",
            existing_type=sa.String(length=36),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "stats_id", existing_type=sa.String(length=36), type_=sa.TEXT(), nullable=True
        )

    with op.batch_alter_table("points_of_interest", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_points_of_interest_trip_id"))
        batch_op.drop_index(batch_op.f("ix_points_of_interest_poi_type"))
        batch_op.create_index(batch_op.f("idx_poi_type"), ["trip_id", "poi_type"], unique=False)
        batch_op.create_index(batch_op.f("idx_poi_trip"), ["trip_id"], unique=False)
        batch_op.create_index(batch_op.f("idx_poi_sequence"), ["trip_id", "sequence"], unique=False)
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "poi_type",
            existing_type=sa.Enum(
                "viewpoint",
                "town",
                "water",
                "accommodation",
                "restaurant",
                "mountain_pass",
                "other",
                name="poi_type_enum",
                native_enum=False,
            ),
            type_=sa.VARCHAR(length=50),
            existing_nullable=False,
        )

    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index("ix_notifications_user_read")
        batch_op.drop_index("ix_notifications_created_at")
        batch_op.create_index(
            batch_op.f("idx_notification_user_unread"),
            ["user_id", "is_read", "created_at"],
            unique=False,
        )
        batch_op.alter_column(
            "is_read",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("likes", schema=None) as batch_op:
        batch_op.drop_index("ix_likes_user_id")
        batch_op.drop_index("ix_likes_trip_id")
        batch_op.drop_index("ix_likes_created_at")
        batch_op.create_index(batch_op.f("idx_like_user"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("idx_like_trip"), ["trip_id"], unique=False)

    with op.batch_alter_table("gpx_files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_gpx_files_trip"), ["trip_id"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_gpx_files_status"), ["processing_status"], unique=False
        )
        batch_op.alter_column(
            "processed_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "uploaded_at",
            existing_type=sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            type_=sa.TIMESTAMP(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "processing_status",
            existing_type=sa.VARCHAR(length=20),
            server_default=sa.text("'pending'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_index("ix_comments_user_id")
        batch_op.drop_index("ix_comments_trip_id")
        batch_op.drop_index("ix_comments_created_at")
        batch_op.create_index(batch_op.f("idx_comment_user"), ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_comment_trip"), ["trip_id", "created_at"], unique=False
        )
        batch_op.alter_column(
            "is_edited",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )

    op.create_table(
        "notification_archive",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("type", sa.VARCHAR(length=20), nullable=False),
        sa.Column("actor_id", sa.VARCHAR(length=36), nullable=True),
        sa.Column("trip_id", sa.VARCHAR(length=36), nullable=True),
        sa.Column("content", sa.TEXT(), nullable=True),
        sa.Column("is_read", sa.BOOLEAN(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("archived_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notification_archive", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_notification_archive_user"), ["user_id", "archived_at"], unique=False
        )

    with op.batch_alter_table("notifications_archive", schema=None) as batch_op:
        batch_op.drop_index("ix_notifications_archive_user")
        batch_op.drop_index("ix_notifications_archive_created_at")

    op.drop_table("notifications_archive")
    # ### end Alembic commands ###
