"""add role column to users table

Revision ID: 9676fc72ca21
Revises: 572d49f6a7f3
Create Date: 2026-01-08 11:54:09.407658+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9676fc72ca21"
down_revision: Union[str, None] = "572d49f6a7f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM type explicitly for PostgreSQL (SQLite ignores this)
    # Using raw SQL because create_type=True doesn't work reliably with batch_alter_table
    connection = op.get_bind()

    # Check if we're using PostgreSQL
    if connection.dialect.name == "postgresql":
        # Create ENUM type if it doesn't exist
        connection.execute(sa.text(
            "DO $$ BEGIN "
            "CREATE TYPE userrole AS ENUM ('USER', 'ADMIN'); "
            "EXCEPTION WHEN duplicate_object THEN null; "
            "END $$;"
        ))

    # Now add the column using the ENUM type
    userrole_enum = sa.Enum("USER", "ADMIN", name="userrole", create_type=False)

    # Add role column with default value 'USER'
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "role",
                userrole_enum,
                nullable=False,
                server_default="USER",
            )
        )
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_role"))
        batch_op.drop_column("role")

    # Drop ENUM type for PostgreSQL (SQLite ignores this)
    connection = op.get_bind()

    if connection.dialect.name == "postgresql":
        # Drop ENUM type using raw SQL
        connection.execute(sa.text("DROP TYPE IF EXISTS userrole;"))

    # ### end Alembic commands ###
