"""create social network tables (likes comments shares notifications)

Revision ID: 9538015d4196
Revises: 6b44dae353a8
Create Date: 2026-01-16 22:41:40.766596+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9538015d4196"
down_revision: Union[str, None] = "6b44dae353a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "trip_visibility",
            existing_type=sa.VARCHAR(length=20),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "trip_visibility",
            existing_type=sa.VARCHAR(length=20),
            server_default=sa.text("'public'"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
