"""Add trip_visibility field to User model

Revision ID: 6b44dae353a8
Revises: 287f9f5c0f3a
Create Date: 2026-01-13 14:46:48.806875+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b44dae353a8"
down_revision: Union[str, None] = "287f9f5c0f3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_trips_public_feed"))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "trip_visibility",
                sa.String(length=20),
                nullable=False,
                server_default="public"
            )
        )
        batch_op.alter_column(
            "role", existing_type=sa.VARCHAR(length=5), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "profile_visibility",
            existing_type=sa.VARCHAR(length=20),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.drop_index(batch_op.f("idx_users_profile_visibility"))
        batch_op.create_index(
            batch_op.f("ix_users_profile_visibility"), ["profile_visibility"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_users_trip_visibility"), ["trip_visibility"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_trip_visibility"))
        batch_op.drop_index(batch_op.f("ix_users_profile_visibility"))
        batch_op.create_index(
            batch_op.f("idx_users_profile_visibility"), ["profile_visibility"], unique=False
        )
        batch_op.alter_column(
            "profile_visibility",
            existing_type=sa.VARCHAR(length=20),
            server_default=sa.text("'public'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(length=5),
            server_default=sa.text("'USER'"),
            existing_nullable=False,
        )
        batch_op.drop_column("trip_visibility")

    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_trips_public_feed"), ["status", "published_at"], unique=False
        )

    # ### end Alembic commands ###
